name: Setup Branch Protection

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/branch-protection.yml'
  workflow_dispatch: # Allow manual trigger

permissions:
  administration: write
  contents: read

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Setup branch protection for main
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            
            try {
              // Configure branch protection rules for main
              const protection = await github.rest.repos.updateBranchProtection({
                owner,
                repo,
                branch: 'main',
                required_status_checks: {
                  strict: true, // Require branches to be up to date before merging
                  contexts: ['test'] // Require the 'test' job from CI workflow to pass
                },
                enforce_admins: false, // Allow admins to bypass (for emergency fixes)
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true, // Dismiss reviews when new commits are pushed
                  require_code_owner_reviews: false,
                  require_last_push_approval: false
                },
                restrictions: null, // No user/team restrictions
                allow_force_pushes: false, // Prevent force pushes
                allow_deletions: false, // Prevent branch deletion
                block_creations: false, // Allow creating the branch
                required_conversation_resolution: true // Require conversation resolution before merge
              });
              
              console.log('✅ Branch protection rules configured for main branch');
              
              // Log the current protection settings
              console.log('Protection settings:');
              console.log('- Required status checks: test');
              console.log('- Required PR reviews: 1');
              console.log('- Dismiss stale reviews: true');
              console.log('- Require up-to-date branches: true');
              console.log('- Block force pushes: true');
              console.log('- Require conversation resolution: true');
              
            } catch (error) {
              if (error.status === 403) {
                console.log('⚠️  Insufficient permissions to set branch protection rules');
                console.log('💡 Repository admin needs to run this workflow or set rules manually');
                console.log('');
                console.log('Manual setup instructions:');
                console.log('1. Go to Settings > Branches');
                console.log('2. Add rule for "main" branch');
                console.log('3. Enable: "Require a pull request before merging"');
                console.log('4. Enable: "Require status checks to pass before merging"');
                console.log('5. Select: "test" status check');
                console.log('6. Enable: "Require branches to be up to date before merging"');
                console.log('7. Enable: "Require conversation resolution before merging"');
                console.log('8. Disable: "Allow force pushes"');
              } else {
                console.error('❌ Error setting up branch protection:', error.message);
                throw error;
              }
            }